In [12]:
import pandas as pd

In [142]:
df = pd.read_csv(
    'Airports.csv'
    , names=['IATA', 'Name', 'City', 'Country', 'Latitude', 'Longitude', 'A', 'B', 'DST', 'Time Zone']
)

In [143]:
df

,IATA,Name,City,Country,Latitude,Longitude,A,B,DST,Time Zone
0,AAC,El Arish International Airport,El Arish,Egypt,31.073299,33.835800,121,2,U,Africa/Cairo
1,AAE,Rabah Bitat Airport,Annaba,Algeria,36.822201,7.809174,16,1,N,Africa/Algiers
2,AAF,Apalachicola Regional Airport,Apalachicola,United States,29.727501,-85.027496,20,-5,A,America/New_York
3,AAH,Aachen-Merzbr√ºck Airport,Aachen,Germany,50.823055,6.186389,623,1,E,Europe/Berlin
4,AAK,Buariki Airport,Buariki,Kiribati,0.185278,173.636993,0,10,U,-
...,...,...,...,...,...,...,...,...,...,...
6066,ZXT,Zabrat Airport,Baku,Azerbaijan,40.495542,49.976807,36,-,-,-
6067,ZYI,Zunyi Xinzhou Airport,Zunyi,China,27.589500,107.000700,2920,8,N,Asia/Shanghai
6068,ZYL,Osmany International Airport,Sylhet Osmani,Bangladesh,24.963200,91.866798,50,6,U,Asia/Dhaka
6069,ZZU,Mzuzu Airport,Mzuzu,Malawi,-11.444700,34.011799,4115,2,U,Africa/Blantyre
6070,ZZV,Zanesville Municipal Airport,Zanesville,United States,39.944401,-81.892097,900,-,-,-

In [144]:
df = df.replace({'-': None}).dropna(axis=0)

In [145]:
df

,IATA,Name,City,Country,Latitude,Longitude,A,B,DST,Time Zone
0,AAC,El Arish International Airport,El Arish,Egypt,31.073299,33.835800,121,2,U,Africa/Cairo
1,AAE,Rabah Bitat Airport,Annaba,Algeria,36.822201,7.809174,16,1,N,Africa/Algiers
2,AAF,Apalachicola Regional Airport,Apalachicola,United States,29.727501,-85.027496,20,-5,A,America/New_York
3,AAH,Aachen-Merzbr√ºck Airport,Aachen,Germany,50.823055,6.186389,623,1,E,Europe/Berlin
5,AAL,Aalborg Airport,Aalborg,Denmark,57.092759,9.849243,10,1,E,Europe/Copenhagen
...,...,...,...,...,...,...,...,...,...,...
6064,ZWA,Andapa Airport,Andapa,Madagascar,-14.651700,49.620602,1552,3,U,Indian/Antananarivo
6065,ZWL,Wollaston Lake Airport,Wollaston Lake,Canada,58.106899,-103.171997,1360,-6,N,America/Regina
6067,ZYI,Zunyi Xinzhou Airport,Zunyi,China,27.589500,107.000700,2920,8,N,Asia/Shanghai
6068,ZYL,Osmany International Airport,Sylhet Osmani,Bangladesh,24.963200,91.866798,50,6,U,Asia/Dhaka
6069,ZZU,Mzuzu Airport,Mzuzu,Malawi,-11.444700,34.011799,4115,2,U,Africa/Blantyre

In [146]:
df[df['Name'].str.contains('√')]

,IATA,Name,City,Country,Latitude,Longitude,A,B,DST,Time Zone
3,AAH,Aachen-Merzbr√ºck Airport,Aachen,Germany,50.823055,6.186389,623,1,E,Europe/Berlin
40,ACD,Alcides Fern√°ndez Airport,Acandi,Colombia,8.516670,-77.300000,50,-5,U,America/Bogota
47,ACN,Ciudad Acu√±a New International Airport,Ciudad Acuna,Mexico,29.332899,-101.098998,1410,-6,S,America/Mexico_City
84,AES,√Ölesund Airport,Alesund,Norway,62.562500,6.119700,69,1,E,Europe/Oslo
101,AGH,√Ñngelholm-Helsingborg Airport,√Ñngelholm,Sweden,56.296101,12.847100,68,1,E,Europe/Stockholm
...,...,...,...,...,...,...,...,...,...,...
6038,ZOS,Ca√±al Bajo Carlos - Hott Siebert Airport,Osorno,Chile,-40.611198,-73.060997,187,-4,S,America/Santiago
6040,ZPC,Puc√≥n Airport,Pucon,Chile,-39.292801,-71.915901,853,-4,S,America/Santiago
6044,ZQW,Zweibr√ºcken Airport,Zweibruecken,Germany,49.209400,7.400560,1132,1,E,Europe/Berlin
6046,ZRH,Z√ºrich Airport,Zurich,Switzerland,47.464699,8.549170,1416,1,E,Europe/Zurich
6054,ZTB,T√™te-√†-la-Baleine Airport,T√™te-√†-la-Baleine,Canada,50.674400,-59.383598,107,-4,A,America/Blanc-Sablon

In [147]:
encodings = {
    '√™' : 'ê'
    , '√º' : 'ü'
    , '√°' : 'ü'
    , '√±' : 'ñ'
    , '√Ö' : 'Å'
    , '√Ñ' : 'Ä'
    , '√†' : 'à'
    , '√∫' : 'ú'
    , '√£': 'ã'
    , '√©' : 'é'
    , '√∏' : 'ø'
    , '√®' : 'è'
    , '√ß' : 'ç'
    , '√≠' : 'í'
    , '√≥' : 'ó'
    , 'Ç' : 'ö'
    , '√•' : 'å'
    , '√é' : 'Î'
    , '√¶' : 'æ'
    , '√â' : 'É'
    , '√¨' : 'ì'
    , '√§' : 'ä'
    , '√ò' : 'Ø'
    , '√á' : 'Ç'
    , '√¢' : 'â'
    , '√Æ' : 'î'
    , '√¢' : 'â'
    , '√§' : 'ä'
    , '√∂' : 'ö'
    , '√∞' : 'ð'
    , '√ú' : 'ü'
    , '√Å' : 'Á'
    , '√µ' : 'õ'
    , '√ì' : 'Ó'
    , '√¥' : 'ô'
    , '√ç' : 'Í'
    , '√ö' : 'Â'
    , '√Ø' : 'ï'
    , '√ñ' : 'Ö'
}

In [148]:
df['Name'].replace(encodings, inplace=True, regex=True)

In [149]:
df

,IATA,Name,City,Country,Latitude,Longitude,A,B,DST,Time Zone
0,AAC,El Arish International Airport,El Arish,Egypt,31.073299,33.835800,121,2,U,Africa/Cairo
1,AAE,Rabah Bitat Airport,Annaba,Algeria,36.822201,7.809174,16,1,N,Africa/Algiers
2,AAF,Apalachicola Regional Airport,Apalachicola,United States,29.727501,-85.027496,20,-5,A,America/New_York
3,AAH,Aachen-Merzbrück Airport,Aachen,Germany,50.823055,6.186389,623,1,E,Europe/Berlin
5,AAL,Aalborg Airport,Aalborg,Denmark,57.092759,9.849243,10,1,E,Europe/Copenhagen
...,...,...,...,...,...,...,...,...,...,...
6064,ZWA,Andapa Airport,Andapa,Madagascar,-14.651700,49.620602,1552,3,U,Indian/Antananarivo
6065,ZWL,Wollaston Lake Airport,Wollaston Lake,Canada,58.106899,-103.171997,1360,-6,N,America/Regina
6067,ZYI,Zunyi Xinzhou Airport,Zunyi,China,27.589500,107.000700,2920,8,N,Asia/Shanghai
6068,ZYL,Osmany International Airport,Sylhet Osmani,Bangladesh,24.963200,91.866798,50,6,U,Asia/Dhaka
6069,ZZU,Mzuzu Airport,Mzuzu,Malawi,-11.444700,34.011799,4115,2,U,Africa/Blantyre

In [150]:
df.to_csv('airports.csv')